<?php

namespace Foundry\Database\Factories;

use Foundry\Foundry;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;

class SupportTicketFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<Model>
     */
    public function modelName()
    {
        return Foundry::$supportTicketModel;
    }

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'name' => fake()->name(),
            'email' => fake()->email(),
            'phone' => fake()->phoneNumber(),
            'subject' => fake()->sentence(),
            'message' => fake()->paragraph(),
            'status' => ['pending', 'replied', 'staff_replied', 'resolved'][rand(0, 3)],
        ];
    }
}
