<?php

namespace Foundry\Database\Factories;

use Foundry\Foundry;
use Foundry\Models\Address;
use Foundry\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * @extends Factory<User>
 */
class UserFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<Model>
     */
    public function modelName()
    {
        return Foundry::$userModel;
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $created_at = fake()->dateTimeBetween('-3 years');
        $gender = ['male', 'female'][rand(0, 1)];

        return [
            'first_name' => fake()->firstName($gender),
            'last_name' => fake()->lastName(),
            'email' => fake()->unique()->safeEmail,
            'gender' => $gender,
            'phone_number' => fake()->e164PhoneNumber(),
            'email_verified_at' => now(),
            'password' => 'password', // password
            'remember_token' => Str::random(10),
            'status' => fake()->randomElement(['active', 'pending']),
            'created_at' => $created_at,
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     *
     * @return static
     */
    public function unverified()
    {
        return $this->state(function (array $attributes) {
            return [
                'email_verified_at' => null,
            ];
        });
    }

    /**
     * Indicate that the model's status should be deactive.
     *
     * @return static
     */
    public function deactive()
    {
        return $this->state(function (array $attributes) {
            return [
                'is_active' => false,
            ];
        });
    }

    /**
     * Indicate that the model should have an address.
     *
     * @return static
     */
    public function withAddress(array $attributes = [])
    {
        return $this->afterCreating(function (User $user) use ($attributes) {
            $user->updateOrCreateAddress(Address::factory()->make($attributes)->toArray());
        });
    }

    /**
     * Configure the model factory.
     */
    public function configure(): static
    {
        return $this;
    }
}
